const technologyOptions = [
    { value: 'AI & Machine Learning', label: 'AI & Machine Learning' },
    { value: 'Android Development', label: 'Android Development' },
    { value: 'Angular', label: 'Angular' },
    { value: 'ASP.NET', label: 'ASP.NET' },
    { value: 'AWS', label: 'AWS' },
    { value: 'Azure', label: 'Azure' },
    { value: 'Blockchain', label: 'Blockchain' },
    { value: 'C', label: 'C' },
    { value: 'C++', label: 'C++' },
    { value: 'C#', label: 'C#' },
    { value: 'Cloud Computing', label: 'Cloud Computing' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'Dart', label: 'Dart' },
    { value: 'Data Science', label: 'Data Science' },
    { value: 'Django', label: 'Django' },
    { value: 'Docker', label: 'Docker' },
    { value: 'Elixir', label: 'Elixir' },
    { value: 'Flutter', label: 'Flutter' },
    { value: 'Fortran', label: 'Fortran' },
    { value: 'Golang', label: 'Golang' },
    { value: 'GraphQL', label: 'GraphQL' },
    { value: 'Hadoop', label: 'Hadoop' },
    { value: 'HTML & CSS', label: 'HTML & CSS' },
    { value: 'iOS Development', label: 'iOS Development' },
    { value: 'Java', label: 'Java' },
    { value: 'JavaScript', label: 'JavaScript' },
    { value: 'Jenkins', label: 'Jenkins' },
    { value: 'Kotlin', label: 'Kotlin' },
    { value: 'Kubernetes', label: 'Kubernetes' },
    { value: 'Laravel', label: 'Laravel' },
    { value: 'MATLAB', label: 'MATLAB' },
    { value: 'MongoDB', label: 'MongoDB' },
    { value: 'MySQL', label: 'MySQL' },
    { value: 'NestJS', label: 'NestJS' },
    { value: 'Next.js', label: 'Next.js' },
    { value: 'Node.js', label: 'Node.js' },
    { value: 'Objective-C', label: 'Objective-C' },
    { value: 'PHP', label: 'PHP' },
    { value: 'PostgreSQL', label: 'PostgreSQL' },
    { value: 'Power BI', label: 'Power BI' },
    { value: 'Python', label: 'Python' },
    { value: 'Quantum Computing', label: 'Quantum Computing' },
    { value: 'R', label: 'R' },
    { value: 'React', label: 'React' },
    { value: 'Redis', label: 'Redis' },
    { value: 'Redux', label: 'Redux' },
    { value: 'Ruby', label: 'Ruby' },
    { value: 'Ruby on Rails', label: 'Ruby on Rails' },
    { value: 'Rust', label: 'Rust' },
    { value: 'SAP', label: 'SAP' },
    { value: 'Scala', label: 'Scala' },
    { value: 'Spring Boot', label: 'Spring Boot' },
    { value: 'SQL', label: 'SQL' },
    { value: 'Swift', label: 'Swift' },
    { value: 'TensorFlow', label: 'TensorFlow' },
    { value: 'Terraform', label: 'Terraform' },
    { value: 'TypeScript', label: 'TypeScript' },
    { value: 'Unity', label: 'Unity' },
    { value: 'Unreal Engine', label: 'Unreal Engine' },
    { value: 'Vue.js', label: 'Vue.js' },
    { value: 'Web3', label: 'Web3' },
    { value: 'WordPress', label: 'WordPress' },
    { value: 'Xamarin', label: 'Xamarin' }
];

export default technologyOptions;
